[sources.filesystem.credentials]
project_id = "gcp-project-id"
private_key = "gcp-project-service-account-private-key"
client_email = "gc-project-service-account-id"

[destination.filesystem.credentials]
project_id = "gcp-project-id"
private_key = "gcp-project-service-account-private-key"
client_email = "gc-project-service-account-id"